### PR TITLE
fix: fix all warnings

### LINKED ISSUE #25: Fix all lint warnings
Image

### PR DESCRIPTION
**Pull request by xStrixU**
Fixes #25

### CODE REVIEW

File: src/components/dashboard/sync/SyncItem.tsx [hunk 1]
```diff
@@ -79,7 +79,7 @@ export const SyncItem = memo<SyncItemProps>(({ sync }) => {
         </div>
       </td>
       <td className="whitespace-nowrap px-6 py-4 text-right text-sm text-gray-500">
-        {sync.syncedArticlesCount ?? 0}
+        {sync.syncedArticlesCount || 0}
```
Comment (Bartek532) [inline src/components/dashboard/sync/SyncItem.tsx:82]: What's the reason behind changing it to logical disjunction?

**Review by Bartek532 — APPROVED** [review]

**Review by Bartek532 — APPROVED** [review]
